name: OllamaEnv
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.11
    - flask=3.0.3
    - langchain=0.2.11
    - pip=24.0
    - pip:
          - ollama==0.3.1
          - langchain-ollama==0.1.0
